---
# - name: Set Locale
#   ansible.builtin.shell:
#     cmd: LC_ALL

- include: user_wrangler.yml
  tags: user

- include_tasks: "install/{{ ansible_facts['os_family'] | default('Suse') }}.yml"
  tags: install

- include_tasks: configure.yml
  tags: configure
