---
namespace: "joe_opensrc"
name: "percona_mongodb"
version: "1.1.0"
description: "Percona MongoDB Wrangler"
license:
  - "GPL-2.0-only"
readme: "README.md"
authors:
  - "Joe OpenSrc"
dependencies:
  "community.general": ">=1.3.0"
tags:
  - mongodb
  - percona
  - database
  - system
repository: "https://github.com/joe-opensrc/ansible-percona-mongodb"
