name: Docker Image CI -- ubuntu:20.04

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -f Dockerfile.ubuntu -t joe-opensrc/ubuntu-psmdb:latest
