name: Docker Image CI -- debian:bullseye

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -f Dockerfile.debian -t joe-opensrc/debian-psmdb:latest
